services:
  nestjs:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app

  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=antifraud